/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemafm;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Geovani
 */
public class DEVOLUCION extends javax.swing.JInternalFrame {

    /**
     * Creates new form DEVOLUCION
     */
    public DEVOLUCION() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        txtReporte = new javax.swing.JTextField();
        txtDevolucion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtGuardar = new javax.swing.JButton();
        txtFechaDevolucion = new javax.swing.JTextField();
        txtModificar = new javax.swing.JButton();
        txtEliminar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        txtFechaRenta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtMora = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setVisible(true);

        jLabel4.setText("NO. DEVOLUCION");

        txtReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReporteActionPerformed(evt);
            }
        });

        jLabel2.setText("NO. REPORTE");

        btnLimpiar.setText("LIMPIAR");

        jLabel5.setText("FECHA RENTA");

        jLabel6.setText("FECHA DEVOLUCION");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("BUSCAR DEVOLUCION");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtGuardar.setText("GUARDAR");
        txtGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGuardarActionPerformed(evt);
            }
        });

        txtModificar.setText("MODIFICAR");

        txtEliminar.setText("ELIMINAR");

        jLabel1.setText("DEVOLUCION DE RENTAS");

        jLabel3.setText("MONTO");

        jLabel7.setText("MORA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(31, 31, 31))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(108, 108, 108))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtFechaRenta, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                                    .addComponent(txtFechaDevolucion)
                                    .addComponent(txtDevolucion)
                                    .addComponent(txtReporte)
                                    .addComponent(txtMonto)
                                    .addComponent(txtMora)))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(163, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGuardar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(59, 59, 59))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtFechaRenta, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtFechaDevolucion, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(txtMora, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 1, Short.MAX_VALUE)
                        .addComponent(txtModificar)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEliminar)
                        .addGap(233, 233, 233))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGuardarActionPerformed
        // TODO add your handling code here:
        
        
         try{
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/sistema_fm", "rex", "polloloco900");
            PreparedStatement pst = cn.prepareStatement("insert into devolucion values(?,?,?,?,?,?)");
            //en la variables pst de tipo coneccion a base de datos inserte 
            
            pst.setString(1, txtDevolucion.getText().trim());
            pst.setString(2, txtReporte.getText().trim());
            
            pst.setString(3, txtMonto.getText().trim());
            pst.setString(4, txtMora.getText().trim());
            pst.setString(5, txtFechaRenta.getText().trim());
            pst.setString(6, txtFechaDevolucion.getText().trim());
            
            
            
            // aca ejecuta el qvery
            
            
            pst.executeUpdate();
             JOptionPane.showMessageDialog(null, " REGISTRO DEVOLUCION CORRECTAMENTE");
            txtDevolucion.setText("");
             txtReporte.setText("");
             txtMonto.setText("");
             txtMora.setText("");
             txtFechaRenta.setText("");
             txtFechaDevolucion.setText("");
             

            
            
            
              
            
            // limpiio registros
          
        }catch (Exception e){
            
        }
        
    }//GEN-LAST:event_txtGuardarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        
        
             try{
        
        Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/sistema_fm", "rex", "polloloco900");
        
        
        PreparedStatement pst = cn.prepareStatement("select * from  reporte where Id_Reporte = ?");
        
        pst.setString(1, txtReporte.getText().trim());
        ResultSet rs = pst.executeQuery();
        if (rs.next()){
                 txtFechaRenta.setText(rs.getString("Fecha_Adquisicion"));
                 txtFechaDevolucion.setText(rs.getString("Fecha_Devolucion"));
                 txtMonto.setText(rs.getString("Total_Renta"));
             }
                
                }catch (Exception e){
        
        }   
       /* PreparedStatement pst2 = cn.prepareStatement("select * from reporte where Fecha_Adquisicion = ?");
        
        pst2.setString(1, txtFechaRenta.getText().trim());
        ResultSet rs2 = pst2.executeQuery();
        
        PreparedStatement pst3 = cn.prepareStatement("select * from reporte where Fecha_Devolucion = ?");
        
        pst3.setString(1, txtFechaDevolucion.getText().trim());
        ResultSet rs3 = pst3.executeQuery();
       */
        /*if(rs.next()){
            
                if(rs2.next()){
                    
                    
                if(rs3.next()){
                                JOptionPane.showMessageDialog(null, "NO TIENE MORA " );
                                
                                
                
                }
                        
            } 
        }else {
                
                JOptionPane.showMessageDialog(null, "HA USTED SE LE  AGREGARA MORA " );
                
            }
        
        
        
          
            
        }catch (Exception e){
        
        }     
        
        
        /*        
 try{
     
     String Fecha_Renta=null;
     String Fecha_Devolucion=null;
     
      Fecha_Renta=txtFechaRenta.getText();
     Fecha_Devolucion=txtFechaDevolucion.getText();
     
     
     if (Fecha_Renta.equals(Fecha_Devolucion)){
         
     
             Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/sistema_fm", "rex", "polloloco900");
            PreparedStatement pst = cn.prepareStatement("select * from clientes where No_Tarjeta = ?");
            
            //aca busca que tiene el txt 
            pst.setString(1, txtBuscar.getText().trim());
            
            /// aca ejecuta el query
            ResultSet rs = pst.executeQuery();
            
            
            if(rs.next()){
          
            
        }catch (Exception e){
        
        }       
    */






             

// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReporteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtDevolucion;
    private javax.swing.JButton txtEliminar;
    private javax.swing.JTextField txtFechaDevolucion;
    private javax.swing.JTextField txtFechaRenta;
    private javax.swing.JButton txtGuardar;
    private javax.swing.JButton txtModificar;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtMora;
    private javax.swing.JTextField txtReporte;
    // End of variables declaration//GEN-END:variables
}
