/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemafm;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Geovani
 */
public class DEVOLUCION extends javax.swing.JInternalFrame {
    private static String db = "sistema_fm";
    private static String user = "root";
    private static String password = "Cagada1234";
    private static String host = "localhost";
    private static String server = "jdbc:mysql://"+ host + "/" +db; 
    private static Float Total = 0.0f;
    /**
     * Creates new form DEVOLUCION
     */
    public DEVOLUCION() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtReporte = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnMora = new javax.swing.JButton();
        txtGuardar = new javax.swing.JButton();
        txtFechaDevolucion = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        txtFechaRenta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtMora = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setVisible(true);

        txtReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReporteActionPerformed(evt);
            }
        });

        jLabel2.setText("NO. REPORTE");

        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        jLabel5.setText("FECHA RENTA");

        jLabel6.setText("FECHA DEVOLUCION");

        btnMora.setBackground(new java.awt.Color(255, 255, 255));
        btnMora.setText("Calcular Mora");
        btnMora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoraActionPerformed(evt);
            }
        });

        txtGuardar.setText("GUARDAR");
        txtGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGuardarActionPerformed(evt);
            }
        });

        jLabel1.setText("DEVOLUCION DE RENTAS");

        jLabel3.setText("MONTO");

        jLabel7.setText("TOTAL");

        jLabel8.setText("MORA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtReporte, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                            .addComponent(txtFechaRenta)
                            .addComponent(txtFechaDevolucion)
                            .addComponent(txtMonto)
                            .addComponent(txtMora, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                            .addComponent(txtTotal))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                                    .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(btnMora, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(74, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(467, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGuardar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFechaRenta, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtFechaDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnMora, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(txtMora, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(95, 95, 95))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(280, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(150, 150, 150)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGuardarActionPerformed
        // TODO add your handling code here:
        
        
         try{
            Connection cn = DriverManager.getConnection(server, user, password);
            PreparedStatement pst = cn.prepareStatement("insert into devolucion values(?,?,?,?,?,?,?)");
            //en la variables pst de tipo coneccion a base de datos inserte 
            
            pst.setString(1, "0");
            pst.setString(2, txtReporte.getText().trim());
            pst.setString(3, txtMonto.getText().trim());
            pst.setString(4, txtMora.getText().trim());
            pst.setString(5, txtFechaRenta.getText().trim());
            pst.setString(6, txtFechaDevolucion.getText().trim());
            pst.setString(7, txtTotal.getText().trim());
            pst.executeUpdate();
            
            
 
            
           
             JOptionPane.showMessageDialog(null, " REGISTRO DEVOLUCION CORRECTAMENTE");
            
             txtReporte.setText("");
             txtMonto.setText("");
             txtMora.setText("");
             txtFechaRenta.setText("");
             txtFechaDevolucion.setText("");
             txtTotal.setText("");

            
            
            
              
            
            // limpiio registros
          
        }catch (Exception e){
            
        }
        
    }//GEN-LAST:event_txtGuardarActionPerformed

    private void btnMoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoraActionPerformed

    try{
        //Llenar txt desde reporte
        Connection cn = DriverManager.getConnection(server, user, password);
        PreparedStatement pst = cn.prepareStatement("select * from  reporte where Id_Reporte = ?");
        pst.setString(1, txtReporte.getText().trim());
        ResultSet rs = pst.executeQuery();
        if (rs.next()){
                 txtFechaRenta.setText(rs.getString("Fecha_Adquisicion"));
                 txtFechaDevolucion.setText(rs.getString("Fecha_Devolucion"));
                 txtMonto.setText(rs.getString("Total_Renta"));           
             }
                
        
        //Calcular mora
        int mora = 0;
         Date date = new Date();
                
         DateFormat myFormat = new SimpleDateFormat("dd/MM/yyyy");
     
         mora = compararfechas(txtFechaDevolucion.getText(), ""+myFormat.format(date));
 
         txtMora.setText(mora + "");
        
         Float monto = Float.parseFloat(txtMonto.getText()); 
         Total =  mora + monto;
         txtTotal.setText(Total +"");
         
        }catch (Exception e){
        
        }   
      
    }//GEN-LAST:event_btnMoraActionPerformed

    private void txtReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReporteActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
             txtReporte.setText("");
             txtMonto.setText("");
             txtMora.setText("");
             txtFechaRenta.setText("");
             txtFechaDevolucion.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    public static ArrayList<Integer> extraerNumeros(String cadena) {
      ArrayList<Integer> todosLosNumeros = new ArrayList<Integer>();
      Matcher encuentrador = Pattern.compile("\\d+").matcher(cadena);
      while (encuentrador.find()) { 
        todosLosNumeros.add(Integer.parseInt(encuentrador.group()));
      } 
      return todosLosNumeros;
    }
    
    
    public static int compararfechas(String fecha, String fecha2){
        
        int dia, mes, año;
        dia = extraerNumeros(fecha).get(0);
        mes = extraerNumeros(fecha).get(1);
        año = extraerNumeros(fecha).get(2);
        
        int dia2, mes2, año2;
        dia2 = extraerNumeros(fecha2).get(0);
        mes2 = extraerNumeros(fecha2).get(1);
        año2 = extraerNumeros(fecha2).get(2);
        
        int mora = 0;
        
        if(dia == dia2 && mes == mes2 && año == año2){
            mora = 0;
 
        }else if(dia < dia2 && mes == mes2 && año == año2){
 
            mora = 25;
   
        }else if(mes < mes2 && año == año2){
            
            mora = 50;
            
        }else if(año < año2){
            //18/05/2020
            mora = 100;
        }
        
        else if (dia > dia2 || mes > mes2 || año > año2) {
            mora = 0;
        }
            
        return mora;
    
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnMora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtFechaDevolucion;
    private javax.swing.JTextField txtFechaRenta;
    private javax.swing.JButton txtGuardar;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtMora;
    private javax.swing.JTextField txtReporte;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
