/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemafm;

import java.awt.List;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SEBAS
 */
public class FormRenta extends javax.swing.JInternalFrame {
    private static String db = "sistema_fm";
    private static String user = "root";
    private static String password = "Cagada1234";
    private static String host = "localhost";
    private static String server = "jdbc:mysql://"+ host + "/" +db; 
    float  fltSubtotal, fltTotal=0;
    String nombreCliente = null;
    private static String fechaDevolucion;
    
    /**
     * Creates new form FormRenta
     */
    public FormRenta() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblArticulosR = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNumeroTarjetaR = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNombreArticuloR = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtSubtotalR = new javax.swing.JTextField();
        txtTotalR = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        txtNombreR = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtGeneroR = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtDescripcionR = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtIdArticuloR = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtTipoArticuloR = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtFechaDevolucionR = new javax.swing.JTextField();
        btnFinalizarCompra = new javax.swing.JButton();
        txtFechaActualR = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtNombreClienteR = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setVisible(true);

        tblArticulosR.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblArticulosR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblArticulosRMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblArticulosR);

        jLabel1.setText("FORMULARIO DE RENTA");

        jLabel2.setText("No. Tarjeta: ");

        jLabel3.setText("Nombre de Articulo : ");

        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel4.setText("SUBTOTAL:");

        txtSubtotalR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubtotalRActionPerformed(evt);
            }
        });

        jLabel5.setText("TOTAL:");

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        jLabel6.setText("Nombre:");

        jLabel7.setText("Genero:");

        jLabel8.setText("Descripcion:");

        jLabel9.setText("Id. Articulo:");

        jLabel10.setText("Tipo: ");

        jLabel11.setText("Fecha:");

        jLabel12.setText("Fecha Devolucion: ");

        btnFinalizarCompra.setText("FINALIZAR COMPRA");
        btnFinalizarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarCompraActionPerformed(evt);
            }
        });

        jLabel13.setText("Nombre de Cliente: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(btnBuscar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtIdArticuloR))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(49, 49, 49)
                                        .addComponent(txtTipoArticuloR, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtGeneroR, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtDescripcionR, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtNombreR, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtSubtotalR, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnAgregar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnFinalizarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel12)))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTotalR, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                    .addComponent(txtFechaDevolucionR))
                                .addGap(39, 39, 39))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombreArticuloR, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                            .addComponent(txtNumeroTarjetaR, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                            .addComponent(txtFechaActualR))
                        .addGap(33, 33, 33)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNombreClienteR, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNumeroTarjetaR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombreArticuloR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtFechaActualR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txtNombreClienteR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(btnBuscar)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtIdArticuloR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel6)
                                    .addComponent(txtNombreR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTipoArticuloR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(txtGeneroR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(txtDescripcionR, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtSubtotalR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 305, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTotalR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(btnFinalizarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtFechaDevolucionR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo  =  new DefaultTableModel();
        modelo.setColumnIdentifiers(new Object[]{"Id_Articulo", "Tipo", "Nombre", "Genero" , "Descripcion", "Precio_Renta"});


        try {
            
            Connection cn = DriverManager.getConnection(server, user, password);
            //Traer informacion sobre articulos
            PreparedStatement pst = cn.prepareStatement("select * from articulos where Nombre = ?");
            pst.setString(1, txtNombreArticuloR.getText().trim());
            ResultSet rs = pst.executeQuery();
            while(rs.next()){
                modelo.addRow(new Object[]{rs.getString("Id_Articulo"), rs.getString("Tipo"),
                rs.getString("Nombre"), rs.getString("Genero"), rs.getString("Descripcion"),rs.getString("Precio_Renta")});
            }
             tblArticulosR.setModel(modelo);
             
             //Traer informacion sobre Cliente
            PreparedStatement pstCliente = cn.prepareStatement("select Nombre from clientes where No_Tarjeta = ?");
            pstCliente.setString(1, txtNumeroTarjetaR.getText().trim());
            ResultSet rs1 = pstCliente.executeQuery();
            while(rs1.next()){
               txtNombreClienteR.setText(rs1.getString("Nombre"));
            }
            
           
        }
        catch(Exception e){}
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtSubtotalRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubtotalRActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtSubtotalRActionPerformed

    private void tblArticulosRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblArticulosRMouseClicked
        // TODO add your handling code here:
        int seleccionar = tblArticulosR.rowAtPoint(evt.getPoint());
        txtIdArticuloR.setText(String.valueOf(tblArticulosR.getValueAt(seleccionar,0)));
        txtTipoArticuloR.setText(String.valueOf(tblArticulosR.getValueAt(seleccionar,1)));
        txtNombreR.setText(String.valueOf(tblArticulosR.getValueAt(seleccionar,2)));
        txtGeneroR.setText(String.valueOf(tblArticulosR.getValueAt(seleccionar,3)));
        txtDescripcionR.setText(String.valueOf(tblArticulosR.getValueAt(seleccionar,4)));
        txtSubtotalR.setText(String.valueOf(tblArticulosR.getValueAt(seleccionar,5)));


    }//GEN-LAST:event_tblArticulosRMouseClicked

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        
        txtFechaDevolucionR.setText( calcularFechaDevolucion(txtFechaActualR.getText()));
        try{
        fltSubtotal = Float.parseFloat(txtSubtotalR.getText());
        fltTotal+=fltSubtotal;
        
            //Guardando en tabla renta el registro de cada renta realizada para calcular bonos.
        Connection cn = DriverManager.getConnection(server,user,password);
        PreparedStatement pstRenta =  cn.prepareStatement("insert into rentas values(?,?,?,?)");
        pstRenta.setString(1,"0");
        pstRenta.setString(2,txtNumeroTarjetaR.getText().trim());
        pstRenta.setString(3,txtNombreArticuloR.getText().trim());
        pstRenta.setString(4,txtFechaActualR.getText().trim());
        pstRenta.executeUpdate();
        
        String strTotal;
        strTotal = Float.toString(fltTotal);
        txtTotalR.setText(strTotal);
       
            
            
        }
        catch(Exception e){
        
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnFinalizarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarCompraActionPerformed
        // TODO add your handling code here:
       
        
       try{
           //Guardando registro de la informacion de la renta en reportes
        Connection cn1 = DriverManager.getConnection(server,user,password);
 
        PreparedStatement pstReporte = cn1.prepareStatement("insert into reporte values (?,?,?,?,?,?,?)");
            pstReporte.setString(1,"0");
            pstReporte.setString(2,txtNumeroTarjetaR.getText().trim());
            pstReporte.setString(3,txtNombreClienteR.getText().trim());
            pstReporte.setString(4,txtFechaActualR.getText().trim());
            pstReporte.setString(5,txtFechaDevolucionR.getText().trim());
            pstReporte.setString(6,txtIdArticuloR.getText().trim());
            pstReporte.setString(7,txtTotalR.getText().trim());
            pstReporte.executeUpdate();
            
            txtNumeroTarjetaR.setText("");
            txtNombreArticuloR.setText("");
            txtFechaActualR.setText("");
            txtNombreClienteR.setText("");
            txtIdArticuloR.setText("");
            txtNombreR.setText("");
            txtTipoArticuloR.setText("");
            txtDescripcionR.setText("");
            txtGeneroR.setText("");
            txtFechaDevolucionR.setText("");
            txtTotalR.setText("");
       }
       catch(Exception e){}
    }//GEN-LAST:event_btnFinalizarCompraActionPerformed


     public static ArrayList<Integer> extraerNumeros(String cadena) {
      ArrayList<Integer> todosLosNumeros = new ArrayList<Integer>();
      Matcher encuentrador = Pattern.compile("\\d+").matcher(cadena);
      while (encuentrador.find()) { 
        todosLosNumeros.add(Integer.parseInt(encuentrador.group()));
      } 
      return todosLosNumeros;
    }
     
public static  String calcularFechaDevolucion(String fechaInicial){
     
          //Calculando fecha de devolucion
        int dia, mes, año;
        dia = extraerNumeros(fechaInicial).get(0);
        mes = extraerNumeros(fechaInicial).get(1);
        año = extraerNumeros(fechaInicial).get(2);
            if (mes == 12) {
                 fechaDevolucion = (dia + "/01/"+(año+1));
            }
            else if (mes == 1 && dia == 30) {
                  fechaDevolucion = ("01/03/"+año);
            }
            else if (mes == 1 && dia == 31) {
                  fechaDevolucion = ("02/03/"+año);
            }
            else if (mes%2 == 1) {
                  fechaDevolucion = ("1/"+(mes+2)+"/"+año);
            }
            else{
                fechaDevolucion = (dia + "/"+(mes+1)+"/"+año);
            }
        
        return fechaDevolucion;
     }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnFinalizarCompra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblArticulosR;
    private javax.swing.JTextField txtDescripcionR;
    private javax.swing.JTextField txtFechaActualR;
    private javax.swing.JTextField txtFechaDevolucionR;
    private javax.swing.JTextField txtGeneroR;
    private javax.swing.JTextField txtIdArticuloR;
    private javax.swing.JTextField txtNombreArticuloR;
    private javax.swing.JTextField txtNombreClienteR;
    private javax.swing.JTextField txtNombreR;
    private javax.swing.JTextField txtNumeroTarjetaR;
    private javax.swing.JTextField txtSubtotalR;
    private javax.swing.JTextField txtTipoArticuloR;
    private javax.swing.JTextField txtTotalR;
    // End of variables declaration//GEN-END:variables
}
